/* Real Vulkan readback through R_InitSamplers and TexMgr_SetFilterModes.
 * From repo root:
 *   p=/tmp/qsvr-aniso; glslc --target-env=vulkan1.1 tests/anisotropy_fixture.comp -o "$p.spv"
 *   cc -std=gnu11 -DUSE_SDL3 -D_GNU_SOURCE -ffunction-sections -fdata-sections \
 *     tests/anisotropy_vulkan_fixture.c Quake/gl_rmisc.c $(pkg-config --cflags --libs sdl3) \
 *     -Wl,--gc-sections,--wrap=vkCreateSampler,--wrap=vkUpdateDescriptorSets -lvulkan -lm -o "$p"
 *   VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json "$p" "$p.spv"
 * Exit 77 means the selected Vulkan device lacks compute or 16x anisotropy.
 */
#include <vulkan/vulkan.h>
#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../Quake/gl_texmgr.c"

#define CHECK(x) do { if (!(x)) { fprintf(stderr,"ANISO_FAILED line=%d: %s\n",__LINE__,#x); exit(1); } } while (0)
#define VK(x) do { VkResult e=(x); if(e!=VK_SUCCESS) { fprintf(stderr,"ANISO_FAILED line=%d: %s=%d\n",__LINE__,#x,e); exit(1); } } while (0)
typedef struct { VkSampler h; VkSamplerCreateInfo ci; } sampler_record_t;
static sampler_record_t samplers[32]; static int nsamplers; static VkSampler selected_sampler;
cvar_t vid_anisotropic={"vid_anisotropic","1",CVAR_ARCHIVE,1}, vid_filter={"vid_filter","1",CVAR_ARCHIVE,1};
void Sys_Printf(const char *f,...) { (void)f; }
void Sys_Error(const char *f,...) { va_list a; va_start(a,f); vfprintf(stderr,f,a); va_end(a); abort(); }
void GL_SetObjectName(uint64_t h,VkObjectType t,const char *n) { (void)h;(void)t;(void)n; }
void GL_WaitForDeviceIdle(void) { VK(vkDeviceWaitIdle(vulkan_globals.device)); }
VkResult __real_vkCreateSampler(VkDevice,const VkSamplerCreateInfo*,const VkAllocationCallbacks*,VkSampler*);
void __real_vkUpdateDescriptorSets(VkDevice,uint32_t,const VkWriteDescriptorSet*,uint32_t,const VkCopyDescriptorSet*);
VkResult __wrap_vkCreateSampler(VkDevice d,const VkSamplerCreateInfo *ci,const VkAllocationCallbacks *a,VkSampler *s)
{ VkResult e=__real_vkCreateSampler(d,ci,a,s); if(e==VK_SUCCESS) { CHECK(nsamplers<(int)countof(samplers)); samplers[nsamplers++] = (sampler_record_t){*s,*ci}; } return e; }
void __wrap_vkUpdateDescriptorSets(VkDevice d,uint32_t n,const VkWriteDescriptorSet *w,uint32_t c,const VkCopyDescriptorSet *p)
{ for(uint32_t i=0;i<n;i++) if(w[i].descriptorType==VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER && w[i].pImageInfo) selected_sampler=w[i].pImageInfo->sampler; __real_vkUpdateDescriptorSets(d,n,w,c,p); }
static int record(VkSampler h, float level)
{ for(int i=nsamplers;i--;) if(samplers[i].h==h) return (!!samplers[i].ci.anisotropyEnable)==(level>1) && fabsf(samplers[i].ci.maxAnisotropy-level)<.01f; return 0; }
static void skip(const char *s) { printf("ANISO_VULKAN_SKIPPED %s\n",s); exit(77); }
static uint32_t memtype(uint32_t bits,VkMemoryPropertyFlags flags)
{ for(uint32_t i=0;i<vulkan_globals.memory_properties.memoryTypeCount;i++) if((bits&(1u<<i)) && (vulkan_globals.memory_properties.memoryTypes[i].propertyFlags&flags)==flags)return i; CHECK(0); return 0; }
static VkDeviceMemory alloc(VkMemoryRequirements r,VkMemoryPropertyFlags f)
{ VkMemoryAllocateInfo a={.sType=VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,.allocationSize=r.size,.memoryTypeIndex=memtype(r.memoryTypeBits,f)}; VkDeviceMemory m; VK(vkAllocateMemory(vulkan_globals.device,&a,NULL,&m)); return m; }
static VkBuffer buffer(VkDeviceSize n,VkBufferUsageFlags usage,VkDeviceMemory *m,void **map)
{ VkBufferCreateInfo c={.sType=VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,.size=n,.usage=usage}; VkBuffer b; VkMemoryRequirements r; VK(vkCreateBuffer(vulkan_globals.device,&c,NULL,&b));vkGetBufferMemoryRequirements(vulkan_globals.device,b,&r);*m=alloc(r,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);VK(vkBindBufferMemory(vulkan_globals.device,b,*m,0));if(map)VK(vkMapMemory(vulkan_globals.device,*m,0,n,0,map));return b; }
static VkShaderModule shader(const char *p)
{ FILE *f=fopen(p,"rb");long n;uint32_t *b;VkShaderModule s;CHECK(f&&!fseek(f,0,SEEK_END)&&(n=ftell(f))>0&&!(n&3)&&!fseek(f,0,SEEK_SET));b=malloc(n);CHECK(b&&fread(b,1,n,f)==(size_t)n&&!fclose(f));VkShaderModuleCreateInfo c={.sType=VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,.codeSize=n,.pCode=b};VK(vkCreateShaderModule(vulkan_globals.device,&c,NULL,&s));free(b);return s; }
static void submit(VkCommandBuffer cb)
{ VK(vkEndCommandBuffer(cb));VkSubmitInfo s={.sType=VK_STRUCTURE_TYPE_SUBMIT_INFO,.commandBufferCount=1,.pCommandBuffers=&cb};VK(vkQueueSubmit(vulkan_globals.queue,1,&s,VK_NULL_HANDLE));VK(vkQueueWaitIdle(vulkan_globals.queue)); }
static void begin(VkCommandBuffer cb)
{ VK(vkResetCommandBuffer(cb,0));VkCommandBufferBeginInfo b={.sType=VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,.flags=VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT};VK(vkBeginCommandBuffer(cb,&b)); }
static void barrier(VkCommandBuffer cb,VkImage image,VkImageLayout old,VkImageLayout next,VkAccessFlags src,VkAccessFlags dst,VkPipelineStageFlags a,VkPipelineStageFlags b,uint32_t levels)
{ VkImageMemoryBarrier x={.sType=VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,.oldLayout=old,.newLayout=next,.srcAccessMask=src,.dstAccessMask=dst,.srcQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED,.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED,.image=image,.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,levels,0,1}};vkCmdPipelineBarrier(cb,a,b,0,0,NULL,0,NULL,1,&x); }
static void sampler_case(float level,qboolean stereo,float expected)
{ vid_anisotropic.value=level;vulkan_globals.stereo_active=stereo;selected_sampler=VK_NULL_HANDLE;R_InitSamplers();qboolean af=R_AnisotropyLevel()>1;VkSampler want=stereo&&af?vulkan_globals.linear_aniso_sampler_lod_bias:(vid_filter.value==1?(af?vulkan_globals.point_aniso_sampler_lod_bias:vulkan_globals.point_sampler_lod_bias):(af?vulkan_globals.linear_aniso_sampler_lod_bias:vulkan_globals.linear_sampler_lod_bias));CHECK(selected_sampler==want);if(!record(want,expected)){fprintf(stderr,"ANISO sampler record level=%g expected=%g handle=%p count=%d\n",level,expected,(void*)want,nsamplers);CHECK(0);} }
int main(int argc,char **argv)
{
	if(argc!=2) { fprintf(stderr,"usage: %s anisotropy_fixture.comp.spv\n",argv[0]); return 2; }
	VkInstance instance;VkApplicationInfo app={.sType=VK_STRUCTURE_TYPE_APPLICATION_INFO,.apiVersion=VK_API_VERSION_1_1};VkInstanceCreateInfo ii={.sType=VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,.pApplicationInfo=&app};if(vkCreateInstance(&ii,NULL,&instance)!=VK_SUCCESS)skip("vkCreateInstance");uint32_t n=0,family=0;VK(vkEnumeratePhysicalDevices(instance,&n,NULL));if(!n)skip("no device");VkPhysicalDevice *g=calloc(n,sizeof(*g));VK(vkEnumeratePhysicalDevices(instance,&n,g));VkPhysicalDevice gpu=VK_NULL_HANDLE;for(uint32_t i=0;i<n&&!gpu;i++){VkPhysicalDeviceFeatures x;vkGetPhysicalDeviceFeatures(g[i],&x);uint32_t q=0;vkGetPhysicalDeviceQueueFamilyProperties(g[i],&q,NULL);VkQueueFamilyProperties *qs=calloc(q,sizeof(*qs));vkGetPhysicalDeviceQueueFamilyProperties(g[i],&q,qs);for(uint32_t j=0;j<q;j++)if(x.samplerAnisotropy&&(qs[j].queueFlags&VK_QUEUE_COMPUTE_BIT)){gpu=g[i];family=j;break;}free(qs);}free(g);if(!gpu)skip("needs compute plus samplerAnisotropy");
	VkPhysicalDeviceProperties props;vkGetPhysicalDeviceProperties(gpu,&props);if(props.limits.maxSamplerAnisotropy<16)skip("needs 16x anisotropy for fixed readback footprint");float priority=1;VkDeviceQueueCreateInfo qi={.sType=VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,.queueFamilyIndex=family,.queueCount=1,.pQueuePriorities=&priority};VkPhysicalDeviceFeatures features={.samplerAnisotropy=VK_TRUE};VkDeviceCreateInfo di={.sType=VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,.queueCreateInfoCount=1,.pQueueCreateInfos=&qi,.pEnabledFeatures=&features};VK(vkCreateDevice(gpu,&di,NULL,&vulkan_globals.device));vkGetDeviceQueue(vulkan_globals.device,family,0,&vulkan_globals.queue);vkGetPhysicalDeviceMemoryProperties(gpu,&vulkan_globals.memory_properties);vulkan_globals.device_features.samplerAnisotropy=VK_TRUE;vulkan_globals.device_properties=props;
	VkCommandPool pool;VkCommandPoolCreateInfo pi={.sType=VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,.queueFamilyIndex=family,.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT};VK(vkCreateCommandPool(vulkan_globals.device,&pi,NULL,&pool));VkCommandBuffer cb;VkCommandBufferAllocateInfo cai={.sType=VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,.commandPool=pool,.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY,.commandBufferCount=1};VK(vkAllocateCommandBuffers(vulkan_globals.device,&cai,&cb));
	VkDescriptorSetLayoutBinding bindings[2]={{0,VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,1,VK_SHADER_STAGE_COMPUTE_BIT},{0,VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,1,VK_SHADER_STAGE_COMPUTE_BIT}};VkDescriptorSetLayoutCreateInfo li={.sType=VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,.bindingCount=1,.pBindings=bindings};VkDescriptorSetLayout tex_layout;VK(vkCreateDescriptorSetLayout(vulkan_globals.device,&li,NULL,&tex_layout));li.pBindings=bindings+1;VkDescriptorSetLayout out_layout;VK(vkCreateDescriptorSetLayout(vulkan_globals.device,&li,NULL,&out_layout));VkDescriptorPoolSize ps[2]={{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,1},{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,1}};VkDescriptorPoolCreateInfo dp={.sType=VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,.maxSets=2,.poolSizeCount=2,.pPoolSizes=ps};VkDescriptorPool descriptor_pool;VK(vkCreateDescriptorPool(vulkan_globals.device,&dp,NULL,&descriptor_pool));VkDescriptorSet sets[2];VkDescriptorSetLayout layouts[2]={tex_layout,out_layout};VkDescriptorSetAllocateInfo dai={.sType=VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,.descriptorPool=descriptor_pool,.descriptorSetCount=2,.pSetLayouts=layouts};VK(vkAllocateDescriptorSets(vulkan_globals.device,&dai,sets));
	VkImage image;VkImageCreateInfo ici={.sType=VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,.imageType=VK_IMAGE_TYPE_2D,.format=VK_FORMAT_R8G8B8A8_UNORM,.extent={128,128,1},.mipLevels=8,.arrayLayers=1,.samples=VK_SAMPLE_COUNT_1_BIT,.tiling=VK_IMAGE_TILING_OPTIMAL,.usage=VK_IMAGE_USAGE_TRANSFER_DST_BIT|VK_IMAGE_USAGE_SAMPLED_BIT};VK(vkCreateImage(vulkan_globals.device,&ici,NULL,&image));VkMemoryRequirements ir;vkGetImageMemoryRequirements(vulkan_globals.device,image,&ir);VkDeviceMemory imem=alloc(ir,0);VK(vkBindImageMemory(vulkan_globals.device,image,imem,0));VkImageViewCreateInfo vi={.sType=VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,.image=image,.viewType=VK_IMAGE_VIEW_TYPE_2D,.format=VK_FORMAT_R8G8B8A8_UNORM,.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,8,0,1}};VkImageView view;VK(vkCreateImageView(vulkan_globals.device,&vi,NULL,&view));
	VkDeviceSize bytes=0;for(int m=0;m<8;m++)bytes+=(VkDeviceSize)(128>>m)*(128>>m)*4;VkDeviceMemory upload_mem;void *upload;VkBuffer upload_buffer=buffer(bytes,VK_BUFFER_USAGE_TRANSFER_SRC_BIT,&upload_mem,&upload);unsigned char *p=upload;int w=128;for(int m=0;m<8;m++,w>>=1)for(int y=0;y<w;y++)for(int x=0;x<w;x++){unsigned char v=m?128:((x&1)?255:0);*p++=v;*p++=v;*p++=v;*p++=255;}begin(cb);barrier(cb,image,VK_IMAGE_LAYOUT_UNDEFINED,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,0,VK_ACCESS_TRANSFER_WRITE_BIT,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,8);VkBufferImageCopy copies[8]={0};VkDeviceSize offset=0;for(int m=0;m<8;m++){int d=128>>m;copies[m]=(VkBufferImageCopy){.bufferOffset=offset,.imageSubresource={VK_IMAGE_ASPECT_COLOR_BIT,(uint32_t)m,0,1},.imageExtent={(uint32_t)d,(uint32_t)d,1}};offset+=(VkDeviceSize)d*d*4;}vkCmdCopyBufferToImage(cb,upload_buffer,image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,8,copies);barrier(cb,image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,VK_ACCESS_TRANSFER_WRITE_BIT,VK_ACCESS_SHADER_READ_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,8);submit(cb);
	texmgr_mutex=SDL_CreateMutex();CHECK(texmgr_mutex);gltexture_t tex={.image_view=view,.descriptor_set=sets[0],.flags=TEXPREF_MIPMAP};active_gltextures=&tex;vulkan_globals.gui_sampler_descriptor_sets[0]=(VkDescriptorSet)1;sampler_case(0,true,1);TexMgr_UpdateTextureDescriptorSets();CHECK(selected_sampler==vulkan_globals.point_sampler_lod_bias);sampler_case(4,true,4);vulkan_globals.stereo_active=false;TexMgr_UpdateTextureDescriptorSets();CHECK(selected_sampler==vulkan_globals.point_aniso_sampler_lod_bias);sampler_case(1,true,props.limits.maxSamplerAnisotropy);
	VkDeviceMemory out_mem;void *out;VkBuffer out_buffer=buffer(128*sizeof(float),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,&out_mem,&out);VkDescriptorBufferInfo bi={out_buffer,0,128*sizeof(float)};VkWriteDescriptorSet write={.sType=VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,.dstSet=sets[1],.dstBinding=0,.descriptorCount=1,.descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,.pBufferInfo=&bi};vkUpdateDescriptorSets(vulkan_globals.device,1,&write,0,NULL);VkPipelineLayoutCreateInfo pli={.sType=VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,.setLayoutCount=2,.pSetLayouts=layouts};VkPipelineLayout pipeline_layout;VK(vkCreatePipelineLayout(vulkan_globals.device,&pli,NULL,&pipeline_layout));VkShaderModule module=shader(argv[1]);VkComputePipelineCreateInfo cp={.sType=VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,.stage={.sType=VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,.stage=VK_SHADER_STAGE_COMPUTE_BIT,.module=module,.pName="main"},.layout=pipeline_layout};VkPipeline pipeline;VK(vkCreateComputePipelines(vulkan_globals.device,VK_NULL_HANDLE,1,&cp,NULL,&pipeline));
	float contrast[2];for(int pass=0;pass<2;pass++){if(pass){sampler_case(1,true,props.limits.maxSamplerAnisotropy);}else {sampler_case(0,true,1);}begin(cb);vkCmdBindPipeline(cb,VK_PIPELINE_BIND_POINT_COMPUTE,pipeline);vkCmdBindDescriptorSets(cb,VK_PIPELINE_BIND_POINT_COMPUTE,pipeline_layout,0,2,sets,0,NULL);vkCmdDispatch(cb,128,1,1);VkBufferMemoryBarrier b={.sType=VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,.srcAccessMask=VK_ACCESS_SHADER_WRITE_BIT,.dstAccessMask=VK_ACCESS_HOST_READ_BIT,.srcQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED,.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED,.buffer=out_buffer,.size=VK_WHOLE_SIZE};vkCmdPipelineBarrier(cb,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_HOST_BIT,0,0,NULL,1,&b,0,NULL);submit(cb);float *v=out;contrast[pass]=0;for(int i=1;i<128;i++)contrast[pass]+=fabsf(v[i]-v[i-1]);contrast[pass]/=127.;}CHECK(contrast[0]<.08f&&contrast[1]>.35f&&contrast[1]>contrast[0]*6);printf("ANISO_VULKAN_PASSED max=%g off_contrast=%g max_contrast=%g production_sampler_and_descriptor_selection\n",props.limits.maxSamplerAnisotropy,contrast[0],contrast[1]);
	VkSampler owned[]={vulkan_globals.point_sampler,vulkan_globals.linear_sampler,vulkan_globals.gui_point_sampler,vulkan_globals.gui_linear_sampler,vulkan_globals.point_aniso_sampler,vulkan_globals.linear_aniso_sampler,vulkan_globals.point_sampler_lod_bias,vulkan_globals.linear_sampler_lod_bias,vulkan_globals.point_aniso_sampler_lod_bias,vulkan_globals.linear_aniso_sampler_lod_bias};for(int i=0;i<(int)countof(owned);i++)if(owned[i])vkDestroySampler(vulkan_globals.device,owned[i],NULL);vkDestroyPipeline(vulkan_globals.device,pipeline,NULL);vkDestroyShaderModule(vulkan_globals.device,module,NULL);vkDestroyPipelineLayout(vulkan_globals.device,pipeline_layout,NULL);vkDestroyBuffer(vulkan_globals.device,out_buffer,NULL);vkFreeMemory(vulkan_globals.device,out_mem,NULL);vkDestroyBuffer(vulkan_globals.device,upload_buffer,NULL);vkFreeMemory(vulkan_globals.device,upload_mem,NULL);vkDestroyImageView(vulkan_globals.device,view,NULL);vkDestroyImage(vulkan_globals.device,image,NULL);vkFreeMemory(vulkan_globals.device,imem,NULL);vkDestroyDescriptorPool(vulkan_globals.device,descriptor_pool,NULL);vkDestroyDescriptorSetLayout(vulkan_globals.device,out_layout,NULL);vkDestroyDescriptorSetLayout(vulkan_globals.device,tex_layout,NULL);SDL_DestroyMutex(texmgr_mutex);vkDestroyCommandPool(vulkan_globals.device,pool,NULL);vkDestroyDevice(vulkan_globals.device,NULL);vkDestroyInstance(instance,NULL);return 0;
}
